library/general/containerresourceratios/template.yaml
Corrected the indentation and moved target as the first property which makes it easier to spot, as well as align with the test of the templates.
=> Fix indentation in resourceratios template

README.md
Recent directory layout changes by @ctab broken end-user instructions. 
Would be nice if there are always working instructions on how to use stuff...
The library repo so far doesn't seem to have people in mind that actually might want to use it. I know this is maybe a harsh critic, I'm still speaking out, because I find the work here really really useful and wish for everyone to use it.
=> Update usage instructions to new directory layout

README.md, library/general/allowedrepos/template.yaml, library/general/block-nodeport-services/template.yaml, library/general/containerlimits/template.yaml, library/general/containerresourceratios/template.yaml, library/general/externalip/template.yaml, library/general/httpsonly/template.yaml, library/general/imagedigests/template.yaml, library/general/requiredlabels/template.yaml, library/general/requiredprobes/template.yaml, library/general/uniqueingresshost/template.yaml, library/general/uniqueserviceselector/template.yaml, library/pod-security-policy/allow-privilege-escalation/template.yaml, library/pod-security-policy/apparmor/template.yaml, library/pod-security-policy/capabilities/template.yaml, library/pod-security-policy/flexvolume-drivers/template.yaml, library/pod-security-policy/forbidden-sysctls/template.yaml, library/pod-security-policy/fsgroup/template.yaml, library/pod-security-policy/host-filesystem/template.yaml, library/pod-security-policy/host-namespaces/template.yaml, library/pod-security-policy/host-network-ports/template.yaml, library/pod-security-policy/privileged-containers/template.yaml, library/pod-security-policy/proc-mount/template.yaml, library/pod-security-policy/read-only-root-filesystem/template.yaml, library/pod-security-policy/seccomp/template.yaml, library/pod-security-policy/selinux/template.yaml, library/pod-security-policy/users/template.yaml, library/pod-security-policy/volumes/template.yaml
Adding description annotations to the templates; these will be used to generate documentation of the available templates (with descriptions, parameters, and sample constraints).
https://github.com/open-policy-agent/gatekeeper-library/issues/28
Signed-off-by: Craig Tabita <ctab@google.com>
=> Add descriptions to templates

library/general/externalip/template.yaml
Typo metadata.annotation --> metadata.annotations
Signed-off-by: Craig Tabita <ctab@google.com>
=> Correct annotations in externalip

.github/workflows/actions.yaml, README.md, library/general/httpsonly/template.yaml, src/general/httpsonly/src.rego, test.sh
replaces https://github.com/open-policy-agent/gatekeeper/pull/821
needs https://github.com/open-policy-agent/opa/issues/2562 + https://github.com/open-policy-agent/opa/issues/2139 for nice coverage enforcement (or we can hack it ... I got the code already, but it's in ruby)
=> add testing

library/pod-security-policy/privileged-containers/samples/psp-privileged-container/constraint.yaml
This is to allow system pods to be created on new nodes during node upgrade, repair, or auto-scaling.
=> exclude kube-system namespace in K8sPSPPrivilegedContainer example

library/pod-security-policy/users/template.yaml, src/pod-security-policy/users/src.rego, src/pod-security-policy/users/src_test.rego
This PR solves [Issue 49](https://github.com/open-policy-agent/gatekeeper-library/issues/49)
- It adds a check for the `runAsNonRoot` securityContext field.
- It adds tests to validate the rule is functioning.
=> Add runAsNonRoot securityContext check

library/experimental/mutation/pod-security-policy/allow-privilege-escalation/samples/default-allow-privilege-escalation/example.yaml, library/experimental/mutation/pod-security-policy/allow-privilege-escalation/samples/mutation.yaml, library/experimental/mutation/pod-security-policy/apparmor/samples/default-apparmor/example.yaml, library/experimental/mutation/pod-security-policy/apparmor/samples/mutation.yaml, library/experimental/mutation/pod-security-policy/capabilities/samples/default-add-capabilities/example.yaml, library/experimental/mutation/pod-security-policy/capabilities/samples/mutation.yaml, library/experimental/mutation/pod-security-policy/read-only-root-filesystem/samples/mutation.yaml, library/experimental/mutation/pod-security-policy/read-only-root-filesystem/samples/read-only-root-filesystem/example.yaml, library/experimental/mutation/pod-security-policy/seccomp/samples/default-seccomp/example.yaml, library/experimental/mutation/pod-security-policy/seccomp/samples/mutation.yaml, library/experimental/mutation/pod-security-policy/selinux/samples/default-selinux/example.yaml, library/experimental/mutation/pod-security-policy/selinux/samples/mutation.yaml, library/experimental/mutation/pod-security-policy/users/samples/mutation-fsGroup.yaml, library/experimental/mutation/pod-security-policy/users/samples/mutation-mustRunAsNonRoot.yaml, library/experimental/mutation/pod-security-policy/users/samples/mutation-runAsGroup.yaml, library/experimental/mutation/pod-security-policy/users/samples/mutation-runAsUser.yaml, library/experimental/mutation/pod-security-policy/users/samples/mutation-supplementalGroups.yaml, library/experimental/mutation/pod-security-policy/users/samples/users/example-nomutation.yaml, library/experimental/mutation/pod-security-policy/users/samples/users/example.yaml, test/bats/test.bats
Re-opening since I can't change target branch of #62 
As discussed on the community call, policies are moved to `library/experimental/mutation/pod-security-policy/`
=> add mutation pod security policies

library/general/containerlimits/samples/container-must-have-limits/example_allowed.yaml, library/general/externalip/samples/allowed-ip/example_disallowed.yaml
Typos in sample resources do not match the allowed/disallowed property.
=> Minor: Typo in name s/disallowed/allowed/

library/general/replicalimits/kustomization.yaml, library/general/replicalimits/samples/replicalimits/constraint.yaml, library/general/replicalimits/samples/replicalimits/example_allowed.yaml, library/general/replicalimits/samples/replicalimits/example_disallowed.yaml, library/general/replicalimits/template.yaml, src/general/replicalimits/src.rego, src/general/replicalimits/src_test.rego
This adds a  new constraint templates and constraints:
- replicalimits
As it says the constraint is aimed at limiting how many replicas can be deployed and making sure a sufficient amount of replicas are deployed in a cluster.
I think this helps with #7 , but i'm not 100% sure.
First time PR'er here so let me know if there's a format I need to follow for PR's etc. (I couldn't see anything)
=> Add min/max constraint examples for Deployments

library/pod-security-policy/host-filesystem/template.yaml, src/pod-security-policy/host-filesystem/src.rego, src/pod-security-policy/host-filesystem/src_test.rego
This change updates the path matching logic to correctly handle "/",
which should match all paths.
Fixes https://github.com/open-policy-agent/gatekeeper-library/issues/96
=> Fix k8spsphostfilesystem path matching

library/general/block-endpoint-edit-default-role/kustomization.yaml, library/general/block-endpoint-edit-default-role/samples/block-endpoint-edit-default-role/constraint.yaml, library/general/block-endpoint-edit-default-role/samples/block-endpoint-edit-default-role/example_allowed.yaml, library/general/block-endpoint-edit-default-role/samples/block-endpoint-edit-default-role/example_disallowed.yaml, library/general/block-endpoint-edit-default-role/template.yaml, src/general/block-endpoint-edit-role/src.rego, src/general/block-endpoint-edit-role/src_test.rego
One policy for issue:
CVE-2021-25740: Endpoint & EndpointSlice permissions allow cross-Namespace forwarding · Issue #103675 · kubernetes/kubernetes
https://github.com/kubernetes/kubernetes/issues/103675
Considering violated system:aggregate-to-edit is automatically created for cluster under v1.22, this Azure Policy will only allow audit/disable (no deny)
=> ClusterRole system:aggregate-to-edit should not allow endpoints permissions

README.md
I've always found the official kustomize documentation to be frustratingly organized and not in-depth enough. Especially for edge cases like ours where users will probably want to use the remote templates, but define their constraints in a local file. As a result, I think we should provide the exact steps for installing with kustomize in the readme.
Here's another repo that provides similarly detailed installation steps: https://metallb.org/installation/
=> Document steps for installing via kustomize in the readme

library/pod-security-policy/capabilities/template.yaml, src/pod-security-policy/capabilities/src.rego, src/pod-security-policy/capabilities/src_test.rego
When checking required drop capabilities, if the container drops "ALL" that should not trigger a violation even if other specifc capabilites are in the requiredDropCapabilities parameter.
=> Treat "ALL" capability as special

library/general/block-wildcard-ingress/kustomization.yaml, library/general/block-wildcard-ingress/samples/block-wildcard-ingress/constraint.yaml, library/general/block-wildcard-ingress/samples/block-wildcard-ingress/disallowed/blank_host.yaml, library/general/block-wildcard-ingress/samples/block-wildcard-ingress/disallowed/host_omitted.yaml, library/general/block-wildcard-ingress/samples/block-wildcard-ingress/disallowed/wildcard_host.yaml, library/general/block-wildcard-ingress/samples/block-wildcard-ingress/example_allowed.yaml, library/general/block-wildcard-ingress/samples/block-wildcard-ingress/example_disallowed.yaml, library/general/block-wildcard-ingress/suite.yaml, library/general/block-wildcard-ingress/template.yaml
Mentioned the reasoning here: https://github.com/kubernetes-sigs/multi-tenancy/issues/1524 , which I've copied below:
> Users can put wildcards (*) in their Ingresses, but I think this can lead to security issues in a multi-tenant environment: https://kubernetes.io/docs/concepts/services-networking/ingress/#hostname-wildcards
> Wildcards in hostnames mean that one tenant could create an ingress for "myservice.example.com" and another tenant could create an ingress for "\*.example.com" or just "\*" and wait. As long as the "myservice.example.com" ingress exists, there's no issue. But if that Ingress is ever removed, even for a second, the traffic will be sent to the other tenant's wildcard Ingress instead, where they can intercept credentials/secrets/etc.
> Additionally, if users leave the …
=> Create block-wildcard-ingress constraint

library/general/noupdateserviceaccount/README.md, library/general/noupdateserviceaccount/kustomization.yaml, library/general/noupdateserviceaccount/samples/noupdateserviceaccount/constraint.yaml, library/general/noupdateserviceaccount/samples/noupdateserviceaccount/example_allowed.yaml, library/general/noupdateserviceaccount/suite.yaml, library/general/noupdateserviceaccount/template.yaml, src/general/noupdateserviceaccount/constraint.tmpl, src/general/noupdateserviceaccount/src.rego, src/general/noupdateserviceaccount/src_test.rego
This policy helps prevent workloads with "update-self" permissions from
escalating further in the cluster by selecting a new service account to
run as. It is especially useful for workloads running in sensitive
namespaces like kube-system, where nearby service accounts are likely to
have cluster admin rights.
@maxsmythe
=> Add noupdateserviceaccount policy to library

library/pod-security-policy/seccomp/suite.yaml, library/pod-security-policy/seccomp/template.yaml, src/pod-security-policy/seccomp/constraint.tmpl, src/pod-security-policy/seccomp/src.rego, src/pod-security-policy/seccomp/src_test.rego
Reworked the Rego policy code for k8spspseccomp so that it will support seccomp configuration found in the pods securityContext while still keeping support for the annotation based seccomp configuration that has been deprecated (to be removed in kubernetes v1.25).
This new policy code was tested with the original unit tests first to ensure backwards compatibility, however I have refactored and expanded the unit tests to cover all locations where a seccomp profile can be found.
The messaging to the user is improved, since there are now 4 locations where a profile can be detected for each container (pod annotation, container annotation, pod securityContext, and container securityContext) I made it clear which location the profile was detected in for each container. I also continue to return …
=> Rework PSP seccomp policy to support the securityContext configuration option

Makefile, library/general/kustomization.yaml, library/kustomization.yaml, library/pod-security-policy/kustomization.yaml, test/bats/test.bats
I noticed some of the policies were missing from kustomization.yaml. I added those missing policies and a test that will ensure the CI pipeline fails if someone forgets to update kustomization.yaml after adding/removing policies.
In order to detect missing entries in the kustomization.yaml, I had to convert our files into the format that kustomize spits out (meaning it adds the apiVersion/kind and removed the leading space in lists)
=> Add all policies to kustomization.yaml and add test

library/general/poddisruptionbudget/template.yaml, src/general/poddisruptionbudget/src.rego
Signed-off-by: Qizhi Liu <joeyliu@rivian.com>
We have had instances where engineers set the replica count to 1 and a pdb set to something else, usually 2 or above. The current error messaging is confusing when this happens as it calls for them to have a pdb minAvailable set to a "positive integer less than 1". 
This messaging is confusing in this case and we would like to make it clear that they should not have a PDB if replicas are set to 1. 
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
99Name: "<redacted>", Namespace: "<redacted>"
100for: "overlays/stage": admission webhook "validation.gatekeeper.sh" denied the request: [pod-distruption-budget]  
Deployment <redacted> has 1 replica(s) but PodDisruptionBudget <redacted> has minAvailable of 2, …
=> Modify pdb error message for clearer instructions if replica is set to 1

library/general/disallowedtags/kustomization.yaml
This should resolve following bug:
```shell
kustomize build .opa-policies` failed exit status 1: Error: accumulating resources: accumulation err='accumulating resources from 'github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/disallowedtags': evalsymlink failure on '.opa-policies/github.com/open-policy-agent/gatekeeper-library/blob/master/library/general/disallowedtags' : lstat .opa-policies/github.com: no such file or directory': evalsymlink failure on '/tmp/kustomize-010481153/blob/master/library/general/disallowedtags' : lstat /tmp/kustomize-010481153/blob: no such file or directory
FATA[0006] Operation has completed with phase: Error
```
This is how my own Kustomize file looks like
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization …
```
=> Fix kustomization.yaml

Makefile, library/general/kustomization.yaml, library/general/storageclass/README.md, library/general/storageclass/kustomization.yaml, library/general/storageclass/samples/storageclass/constraint.yaml, library/general/storageclass/samples/storageclass/example_allowed_pvc.yaml, library/general/storageclass/samples/storageclass/example_allowed_ss.yaml, library/general/storageclass/samples/storageclass/example_disallowed_pvc_badname.yaml, library/general/storageclass/samples/storageclass/example_disallowed_pvc_nonamename.yaml, library/general/storageclass/samples/storageclass/example_disallowed_ssvct_badnamename.yaml, library/general/storageclass/samples/storageclass/example_disallowed_ssvct_nonamename.yaml, library/general/storageclass/samples/storageclass/example_inventory_allowed_storageclass.yaml, library/general/storageclass/suite.yaml, library/general/storageclass/sync.yaml, library/general/storageclass/template.yaml, library/general/uniqueingresshost/samples/unique-ingress-host/example_allowed.yaml, src/general/storageclass/constraint.tmpl, src/general/storageclass/src.rego, src/general/storageclass/src_test.rego, test/bats/sync.yaml, test/bats/test.bats
This change checks statefulsets and pvc's to see if a storage class is specified and valid. This enables problems to be detected at the time the objects are loaded into the cluster rather then much later. This requires a lot less cleanup to happen to fix the misconfiguration.
=> Add checks for storage class usage

library/general/storageclass/template.yaml, src/general/storageclass/constraint.tmpl
* Capitalize Gatekeeper as it is a proper noun.
=> fix: Capitalize Gatekeeper

library/general/storageclass/template.yaml, src/general/storageclass/src.rego, src/general/storageclass/src_test.rego
`results` before:
```
{{"msg": "pvc did not specify a valid storage class name <fast>. Must be one of []"}}
```
`results` after:
```
{{"msg": "StorageClasses not synced. Gatekeeper may be misconfigured. Please have a cluster-admin consult the documentation."}, {"msg": "pvc did not specify a valid storage class name <fast>. Must be one of []"}}
```
=> Fix storageclass no datasync test

library/general/block-loadbalancer-services/kustomization.yaml, library/general/block-loadbalancer-services/samples/block-load-balancer/constraint.yaml, library/general/block-loadbalancer-services/samples/block-load-balancer/example_allowed.yaml, library/general/block-loadbalancer-services/samples/block-load-balancer/example_disallowed.yaml, library/general/block-loadbalancer-services/suite.yaml, library/general/block-loadbalancer-services/template.yaml, library/general/kustomization.yaml, src/general/block-loadbalancer-services/constraint.tmpl, src/general/block-loadbalancer-services/src.rego, src/general/block-loadbalancer-services/src_test.rego
In some environments we'd like the cluster customers to use the pre-provisioned Ingress Controllers to expose their workloads to the outside world.  This policy allows the cluster administrator to block the creation of LoadBalancer services, which can lead to provisioning costly cloud resources (LBs).  This policy along with the one for NodePorts, on which this one is based, also prevent customers from exposing their workload in an unexpected and potentially unmonitored way, which can present a security issue.
=> Added policy to block LoadBalancer services

library/general/allowedrepos/template.yaml, library/general/block-endpoint-edit-default-role/template.yaml, library/general/containerlimits/template.yaml, library/general/containerresources/template.yaml, library/general/requiredlabels/template.yaml, library/general/requiredprobes/template.yaml, src/general/allowedrepos/constraint.tmpl, src/general/block-endpoint-edit-default-role/constraint.tmpl, src/general/containerlimits/constraint.tmpl, src/general/containerresources/constraint.tmpl, src/general/requiredlabels/constraint.tmpl, src/general/requiredprobes/constraint.tmpl, website/docs/allowedrepos.md, website/docs/block-endpoint-edit-default-role.md, website/docs/containerlimits.md, website/docs/containerresources.md, website/docs/requiredlabels.md, website/docs/requiredprobes.md
remove Kubernetes from titles as all the policies are Kubernetes policies
=> remove Kubernetes from policy titles

artifacthub/library/general/uniqueingresshost/1.0.0/sync.yaml, library/general/uniqueingresshost/sync.yaml
Ingress went GA, but the sync object for the unique ingress host policy is only syncing previous API versions of the object.
This PR updates the sync object to include `v1` of the API
=> Add v1 Ingress version to uniqueingresshost sync object

.github/workflows/website.yaml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> workflow: update set-output handling

.github/stale.yml
**What this PR does / why we need it**: Adding stale bot config to handle old stale issues/prs
Fixes #
=> chore: adding stale bot

scripts/artifacthub/hub.go, scripts/artifacthub/hub_test.go
Currently, we are checking the template hash from a local file. This requires a constant version upgrade when we add new template files and incrementally update it before merging. This is incorrect since for a new file, the version would start at `1.0.0`.
With this fix, we are now validating the hash of the template file from GitHub to the hash of the local template file. So when a contributor is trying to create a new template file, it will skip the version check and perform the same for an existing template file for a potential version bump.
Fixes #331 
**Special notes for your …
=> fix: fixes version check for Artifact Hub generation

.github/workflows/workflow.yaml
**What this PR does / why we need it**: update integration test to include Gatekeeper 3.13
=> chore: update integration test to Gatekeeper 3.13

.github/dependabot.yml
**What this PR does / why we need it**: group github-actions dependabot PRs
=> chore: group github-actions dependabot PRs

.github/dependabot.yml
**What this PR does / why we need it**: We should updates all the docusaurus modules at once.
=> chore: group docusaurus npm updates

artifacthub/library/general/verifydeprecatedapi/1.0.0/samples/verify-1.22/constraint.yaml, library/general/verifydeprecatedapi/samples/verify-1.22/constraint.yaml, website/docs/validation/verifydeprecatedapi.md
The example for the verifydeprecatedapi-1.22 constraint should say "scheduling.k8s.io" instead of "scheduling.k8s.io/v1beta1" for the apiGroup match kind. Otherwise, the constraint will not properly match the deprecated API resources.
Fixes #
=> fix: api groups in constraint 1.22

mutation/pod-security-policy/allow-privilege-escalation/samples/mutation.yaml, mutation/pod-security-policy/capabilities/samples/mutation-assign.yaml, mutation/pod-security-policy/capabilities/samples/mutation-modifyset.yaml, mutation/pod-security-policy/read-only-root-filesystem/samples/mutation.yaml, mutation/pod-security-policy/seccomp/samples/mutation.yaml, mutation/pod-security-policy/selinux/samples/mutation.yaml, mutation/pod-security-policy/users/samples/mutation-fsGroup.yaml, mutation/pod-security-policy/users/samples/mutation-mustRunAsNonRoot.yaml, mutation/pod-security-policy/users/samples/mutation-runAsGroup.yaml, mutation/pod-security-policy/users/samples/mutation-runAsUser.yaml, mutation/pod-security-policy/users/samples/mutation-supplementalGroups.yaml, website/docs/mutation-examples/allow-privilege-escalation.md, website/docs/mutation-examples/capabilities.md, website/docs/mutation-examples/read-only-root-filesystem.md, website/docs/mutation-examples/seccomp.md, website/docs/mutation-examples/selinux.md, website/docs/mutation-examples/users.md
the sample mutate assign api is too old
Fixes #444
already run
I fail to find the test framework for mutate
=> bump mutation cr from alpha to v1

artifacthub/library/pod-security-policy/allow-privilege-escalation/1.1.0/samples/psp-allow-privilege-escalation-container/constraint.yaml, artifacthub/library/pod-security-policy/allow-privilege-escalation/1.1.0/samples/psp-allow-privilege-escalation-container/example_allowed_exempt.yaml, artifacthub/library/pod-security-policy/allow-privilege-escalation/1.1.0/suite.yaml, library/pod-security-policy/allow-privilege-escalation/samples/psp-allow-privilege-escalation-container/constraint.yaml, library/pod-security-policy/allow-privilege-escalation/samples/psp-allow-privilege-escalation-container/example_allowed_exempt.yaml, library/pod-security-policy/allow-privilege-escalation/suite.yaml, website/docs/validation/allow-privilege-escalation.md
I recently found (#584) that some K8sNativeValidation implementations of certain templates that iterate over and exempt containers by image had a bug preventing the exemption logic from working.
The k8spspallowprivilegeescalationcontainer turns out not to have this problem, as proved by the passing tests with the addition of an image exemption suite test.
=> chore(k8spspallowprivilegeescalationcontainer): suite test confirming exemptImages
