- README.md
Reverts open-policy-agent/gatekeeper-library#37
This should not have been submitted:
* DCO was not present
* CLA was not signed
> Revert "Update usage instructions to new directory layout"

- library/general/externalip/kustomization.yaml
- library/general/externalip/samples/allowed-ip/constraint.yaml
- library/general/externalip/samples/allowed-ip/example_allowed.yaml
- library/general/externalip/samples/allowed-ip/example_denied.yaml
- library/general/externalip/template.yaml
- src/general/externalip/src.rego
- src/general/externalip/src_test.rego
Add constraint template & samples for restricting service external IPs to an allowlist.
> External IP constraints

- .github/workflows/workflow.yaml
> update release branch for e2e

- library/pod-security-policy/users/template.yaml
- src/pod-security-policy/users/src.rego
- src/pod-security-policy/users/src_test.rego
Fixes #60 
Signed-off-by: Max Smythe <smythe@google.com>
> Handle false security context values correctly

- library/general/kustomization.yaml
Adding missing kustomization resources
> Adding missing kustomization resources

- .github/workflows/workflow.yaml
> update test matrix

- library/general/allowedrepos/samples/repo-must-be-openpolicyagent/constraint.yaml
Fixes #80 
Signed-off-by: Max Smythe <smythe@google.com>
> Add anchoring to allowedrepos example

- test/bats/test.bats
> fix curl image

- .github/workflows/workflow.yaml
- Makefile
> update test matrix and dependencies

- library/general/kustomization.yaml
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
> add general/replicalimits and general/requiredannotations folders to the kustomization YAML file

- library/general/block-endpoint-edit-default-role/template.yaml
- library/general/uniqueingresshost/template.yaml
- library/general/uniqueserviceselector/template.yaml
Clarify the purpose of several templates and their limitations.
> Add explanations to ConstraintTemplates

- library/pod-security-policy/host-network-ports/template.yaml
Signed-off-by: juliankatz <juliankatz@google.com>
> Fix a typo: feilds --> fields

- library/general/containerlimits/template.yaml
- library/general/containerresourceratios/template.yaml
- src/general/containerlimits/src.rego
- src/general/containerlimits/src_test.rego
- src/general/containerresourceratios/src.rego
Fixes #154
Signed-off-by: Max Smythe <smythe@google.com>
> Recognize decimal-based memory limits

- library/general/automount-serviceaccount-token/suite.yaml
Signed-off-by: juliankatz <juliankatz@google.com>
> Add a suite.yaml file for automount template

- library/general/containerresourceratios/suite.yaml
This suite.yaml file was missing one of the examples.
Signed-off-by: juliankatz <juliankatz@google.com>
> Update suite.yaml for containerresourceratios

- .github/workflows/workflow.yaml
> chore: bump gk and opa version for tests

- library/pod-security-policy/README.md
- scripts/website/generate.go
- website/docs/pspintro.md
- website/docusaurus.config.js
- website/static/index.html
> fix: updates base url of website

- .github/workflows/workflow.yaml
- README.md
- website/docs/httpsonly.md
- website/docs/intro.md
add docs website generation as a ci gate
> ci: require website gen

- website/docusaurus.config.js
> feat: adds search in GKL website

- README.md
- artifacthub/artifacthub-repo.yml
- website/docs/intro.md
> feat: adds artifacthub  Verified Publisher

- website/docs/replicalimits.md
> fix: linking correct reources in replicalimit example

- go.work
Signed-off-by: Andrew Peabody <andrewpeabody@google.com>
> feat: add support for go multi-module workspace

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- docs/design/README.md
- website/docs/intro.md
Signed-off-by: Rita Zhang <rita.z.zhang@gmail.com>
> Add docs and PR template and updating versioning

- Makefile
- scripts/artifacthub/hub.go
- scripts/artifacthub/hub_test.go
- scripts/artifacthub/testdata/artifacthub-pkg.yml
> chore: check version

- .github/workflows/website.yaml
- website/docusaurus.config.js
> docs: adds google analytics tracking

- library/pod-security-policy/README.md
- website/docs/pspintro.md
Fixing few things in README:
- Typos
- Table spacing
- Inclusive terminology. Replaced whitelist with approved list
No issues to reference
Trivial changes to README.
> Updating typos, inclusive verbiage

- go.work.sum
- scripts/require-sync/go.mod
- scripts/require-sync/main.go
- scripts/require-sync/main_test.go
Signed-off-by: Andrew Peabody <andrewpeabody@google.com>
Prevent regression of https://github.com/open-policy-agent/gatekeeper-library/issues/264#issuecomment-1349020755
Fixes #264 
https://github.com/open-policy-agent/gatekeeper-library/pull/269 needs to be merged first (CI)
> feat: validate requiresSyncData keys

- artifacthub/library/general/poddisruptionbudget/1.0.2/samples/poddisruptionbudget/example_inventory_allowed3.yaml
- library/general/poddisruptionbudget/samples/poddisruptionbudget/example_inventory_allowed3.yaml
**What this PR does / why we need it**: This PR fixes a faulty test to make sure ci do not throw error
Fixes #276 
> fix: pdb example breaking ci

- artifacthub/library/general/poddisruptionbudget/1.0.2/samples/poddisruptionbudget/example_inventory_allowed3.yaml
- library/general/poddisruptionbudget/samples/poddisruptionbudget/example_inventory_allowed3.yaml
Reverts open-policy-agent/gatekeeper-library#280
> fix: Revert "fix: pdb example breaking ci"

- artifacthub/library/general/poddisruptionbudget/1.0.2/samples/poddisruptionbudget/example_allowed_deployment4.yaml
- library/general/poddisruptionbudget/samples/poddisruptionbudget/example_allowed_deployment4.yaml
- test/bats/test.bats
- website/docs/poddisruptionbudget.md
> fix: pdb non matching test case

- README.md
- website/docs/intro.md
> Fix typo contraints -> constraints

- artifacthub/library/general/disallowedtags/1.0.0/suite.yaml
- artifacthub/library/general/externalip/1.0.0/suite.yaml
- artifacthub/library/general/imagedigests/1.0.0/suite.yaml
- artifacthub/library/general/replicalimits/1.0.0/suite.yaml
- artifacthub/library/general/requiredannotations/1.0.0/suite.yaml
- artifacthub/library/general/requiredlabels/1.0.0/suite.yaml
- artifacthub/library/general/requiredprobes/1.0.0/suite.yaml
- artifacthub/library/general/uniqueingresshost/1.0.0/suite.yaml
- artifacthub/library/general/uniqueingresshost/1.0.1/suite.yaml
- artifacthub/library/general/uniqueingresshost/1.0.2/suite.yaml
- artifacthub/library/general/uniqueserviceselector/1.0.0/suite.yaml
- artifacthub/library/general/uniqueserviceselector/1.0.1/suite.yaml
- library/general/disallowedtags/suite.yaml
- library/general/externalip/suite.yaml
- library/general/imagedigests/suite.yaml
- library/general/replicalimits/suite.yaml
- library/general/requiredannotations/suite.yaml
- library/general/requiredlabels/suite.yaml
- library/general/requiredprobes/suite.yaml
- library/general/uniqueingresshost/suite.yaml
- library/general/uniqueserviceselector/suite.yaml
- website/docs/disallowedtags.md
- website/docs/externalip.md
- website/docs/imagedigests.md
- website/docs/replicalimits.md
- website/docs/requiredannotations.md
- website/docs/requiredlabels.md
- website/docs/requiredprobes.md
- website/docs/uniqueingresshost.md
- website/docs/uniqueserviceselector.md
**What this PR does / why we need it**: Making sure the test names are correct for all `suite.yaml`
Fixes #
> fix: correcting respective test case names

- artifacthub/library/general/verifydeprecatedapi/1.0.0/samples/verify-1.22/constraint.yaml
- library/general/verifydeprecatedapi/samples/verify-1.22/constraint.yaml
- website/docs/validation/verifydeprecatedapi.md
**Special notes for your reviewer**: This only fixes the sample, so I didn't bump the constraint version
> fix: add missing quote, remove stray space

- website/sidebars.js
> Fix: verifydepricatedapi not showing up in website sidebar

- README.md
- website/docs/intro.md
Ref - https://github.com/open-policy-agent/gatekeeper-library/pull/285#discussion_r1089590219
Fixes #
> docs: adds intent of Validation and Mutation

- artifacthub/library/general/storageclass/1.0.0/samples/storageclass/example_allowed_ss.yaml
- artifacthub/library/general/storageclass/1.0.0/samples/storageclass/example_disallowed_ssvct_badnamename.yaml
- artifacthub/library/general/storageclass/1.0.0/samples/storageclass/example_disallowed_ssvct_nonamename.yaml
- artifacthub/library/general/storageclass/1.0.1/samples/storageclass/example_allowed_ss.yaml
- artifacthub/library/general/storageclass/1.0.1/samples/storageclass/example_disallowed_ssvct_badnamename.yaml
- artifacthub/library/general/storageclass/1.0.1/samples/storageclass/example_disallowed_ssvct_nonamename.yaml
- library/general/storageclass/samples/storageclass/example_allowed_ss.yaml
- library/general/storageclass/samples/storageclass/example_disallowed_ssvct_badnamename.yaml
- library/general/storageclass/samples/storageclass/example_disallowed_ssvct_nonamename.yaml
- website/docs/validation/storageclass.md
Fixes https://github.com/kubernetes/k8s.io/issues/4780
> chore: update k8s.gcr.io to registry.k8s.io

- .github/dependabot.yml
This PR enables dependabot to update Gomod and GitHub action dependencies.
Fixes #321
> feat: enables dependabot

- .github/workflows/workflow.yaml
Add CI test coverage for Gatekeeper 3.12
> feat: add Gatekeeper 3.12 to CI

- .github/workflows/workflow.yaml
> chore: update workflow CI for GK 3.14

- artifacthub/library/pod-security-policy/allow-privilege-escalation/1.1.0/samples/psp-allow-privilege-escalation-container/constraint.yaml
- library/pod-security-policy/allow-privilege-escalation/samples/psp-allow-privilege-escalation-container/constraint.yaml
- website/docs/validation/allow-privilege-escalation.md
s/existant/existent/ in library/pod-security-policy/allow-privilege-escalation/samples/psp-allow-privilege-escalation-container/constraint.yaml
> fix(k8spspallowprivilegeescalationcontainer): typo fix

- library/general/kustomization.yaml
**What this PR does / why we need it**: Fixes CI issues - https://github.com/open-policy-agent/gatekeeper-library/actions/runs/12808354026/job/35742115770?pr=621
Fixes #
> adding allowedrepov2 to kustomization.yaml

- .github/workflows/scripts.yaml
**What this PR does / why we need it**: This should fix CI lint errors - https://github.com/open-policy-agent/gatekeeper-library/actions/runs/14041769709/job/39313397476 - on other PRs.
Fixes #
> updating lint version

- .github/workflows/scripts.yaml
- .golangci.yaml
**What this PR does / why we need it**: This should fix CI errors in lint - https://github.com/open-policy-agent/gatekeeper-library/actions/runs/14182596560/job/39731885987?pr=638
Fixes #
> migrating lint configs to v2

- .github/workflows/workflow.yaml
> ci: updating GK versions in test

- .github/workflows/workflow.yaml
- Makefile
- test/bats/test.bats
> chore: updating GK and dep versions
